### ISSUE TITLE
Abandon classes

### ISSUE THREAD

**Issue by robinpokorny** [exercism/javascript#274] opened 2017-04-19 21:03 UTC
Right now all (all I've seen) exercises use and require classes to be exported. In fact, a simple static function would suffice. As seen in this example:

**Before**
```js
class Bob {
  hey(message) { … }
}

export default Bob;
```

**After**
```js
export default (message) => { … }
```

Instead of focusing on the important part, developers are forced to apply this pattern. I'd also argue that it promotes a bad habit of classes overuse.

Maybe there is a hidden reason, in that case, please let me know of it.

**Comment by rchavarria** [comment] 2017-04-21 10:16
There is a lot of discussions about use classes or not in JavaScript.

In fact, we discussed that in the past, but I don't find any link to those discussions, sorry. They probably took place on xjavascript track. @matthewmorgan Do you remember about this?

Anyway, we decided to use the *classy* approach in this track, not because it's a better practice, or a better approach, but because it was a new feature of ECMAScript, and this track is focused on new features.

So, classes were a great candidate to show users a new feature of the language. It may seem overwhelming for some exercises, but it's very important to have some coherence on exercises. We needed to make a decision. It may not be the best one.

Anyway, it would be interesting to know about other opinions, @exercism/javascript ?

**Comment by matthewmorgan** [comment] 2017-04-21 11:39
@rchavarria as I recall, we made this change both for the reason you mentioned, and to keep the API consistent for the first several exercises.  Later we deviate from this to challenge the user and show additional approaches.

Having said that, classes in ES6 are syntactic sugar over ordinary functions.  This in itself is an important lesson to learn.  @robinpokorny if the user preferred, it would be possible to do this:

```javascript
class Bob {
  hey(message) { … }
}

export default Bob;
```

could be instead written as:

```javascript
export default () => {
    return {
        hey: (message) => {... }
    }
}
```

**Comment by robinpokorny** [comment] 2017-04-21 11:53
@rchavarria I do not want to propose not to use classes at all. There surely are use cases when classes are great (and few when their use is matter of opinion). What I dislike is use of classes for simple stateless single data transformation. There should be an excersise that requires a class and another one that requires some advenced class magic ;)

@matthewmorgan The second example is shorter and I like it more; yet it still could be confusing for some users.

BTW it can be written as:

```js
export default () => ({
  hey: () => {…}
})
```

**Comment by matthewmorgan** [comment] 2017-04-21 13:29
@robinpokorny yes that syntax is nice.

I think that we do not want to have the beginner on the track switch back and forth between classes and functions for the first several exercises.

The use of classes in JavaScript is controversial, and I think arguments can be made on either side.  I feel like we've already discussed this in the past and made a decision to use this approach, but if:

1. A compelling case is made to switch
2. The APIs can be consistent for at least the first 10-12 exercises for newbies
3. We have contributors who can commit to doing the work

...then I would feel OK about it.  But I also feel fine keeping things the way they are, and maybe just adding some hints for the use of classes or plain functions would be better, good for people to learn, and much less work for the contributors and maintainers.

**Comment by rchavarria** [comment] 2017-04-25 15:04
Absolutely! @matthewmorgan explained it really well! Thanks!

I see your point @robinpokorny, but I agree with @matthewmorgan. I prefer having a consistent way of requiring users to implement the first exercises. That means, that it feels overwhelming to a user with some experience to create a class for a task that could be solved with a very simple function.

**Comment by tejasbubane** [comment] 2017-04-25 16:30
I see the first two exercises [hello-world](https://github.com/exercism/xecmascript/blob/master/exercises/hello-world/hello-world.spec.js) and [leap](https://github.com/exercism/xecmascript/blob/master/exercises/leap/leap.spec.js) expect the solution to be a `function` and not `class`. Later ones are all classes I guess. Since this is a gradual transition from functions to classes, I guess this is not an issue. Or should we make it all consistent everywhere? What do you think?

Personally, I don't even mind randomly switching between functions and classes since that is what we do everyday with programming, not everything is a function, not everything is a class. The specs tell me what to do 😄 .

**Comment by rchavarria** [comment] 2017-04-26 15:07
I'd prefer keeping the consistency. Of course, real worl is quite different. But think of totally newbies. They'll find it confusing to switch one way to another.

I'm not saying that classes are *the* right way, but it makes sense for later exercises, and it's a ES6 feature, what makes it perfect to use in this track.

**Comment by tejasbubane** [comment] 2017-04-26 15:52
@rchavarria Cool, I opened a PR to change `hello-world` and `leap` to class-based approach.

**Comment by c-dante** [comment] 2018-07-20 03:07
I don't want to dredge this up, but I just want to be told no :)

I'm currently a mentor over on the javascript track for v2, and I've seen maybe 30 or so solutions for these beginning exercises go by.

I'd say about 1/3 of people have been curious why a class based solution is required to pass the tests -- especially since in native, something like this doesn't work:

```js
const Pt = (x, y) => ({ x, y });
console.log(new Pt(1, 2));
// > Uncaught TypeError: Pt is not a constructor
// If it works for you, are you sure it's not getting transpiled to `function`?
```

Does it make sense to ease into classes / inheritance in JS? Start off with exporting just a function to pass the tests then build up to a class based instance solution when it makes sense? Things like the `Forth` problem with state across executions comes to mind.

Anywho, been fun guiding people along the right path, but the more of this I see:
```js
class Year { ... }
class Leap extends Year {
  isLeap() { ... }
}
```

The less I thing we're going in the right direction here.

**Comment by c-dante** [comment] 2018-07-20 13:48
Sounds good to me! I'd love to contribute in any way I can -- I really like the low barrier to entry that exercism provides especially as an entry point for people new and experienced alike.

**Comment by tejasbubane** [comment] 2018-07-23 07:56
We recently had a discussion in slack channels of both `javascript` and `ecmascript` tracks regarding this. I agree with the fact that we should not impose any rules in the implementation details. However, I don't have a strong opinion on classes or functions. If a lot of people prefer functions, we can go that way.

**Comment by c-dante** [comment] 2018-07-23 17:08
Sounds good! This is going to be a tough issue since it's always going to bleed a bit into opinion, but I think as long as we have the beginning track of exercises introduce the concepts and build on it, we'll be in a good place.

To me, starting from pure arrow functions, then classes, finally end with `function` and `prototype`, which delves into the nitty gritty a bit more.

Having the early tests expect pure functions and explore the different primitives (numbers, strings, arrays, objects) and require some control flow. Then introduce functions as a first-class citizen (passing in predicates to your methods to then call). Finally, introduce stateful objects with `class`.

Just thinking out loud.

**Comment by kybernetikos** [comment] 2018-07-23 19:03
I think there's some confusion here to do with the 'class' keyword.  As far as I'm concerned, this is not to do with use of the 'class' keyword, it's to do with tests calling 'new' on students code when just running a function would make just as much sense.

Calling 'new' on students code forces them into a particular way of framing their solution, and for many of the problems it's actually a worse way.  

It should be down to the student to decide on whether to use a functional or an OO approach, and it's the kind of thing that the mentors can discuss with them.

**Comment by c-dante** [comment] 2018-07-23 19:08
@kybernetikos so that's the problem, right? If the test is expecting a function prototype then you need to give a function that works with `new`. At the same time, you really shouldn't solve a pure function spec by passing a class -- no matter how you slice it, the test is going to dictate the final shape of the solution. You simply cannot have both worlds without some odd work.

That being said, forcing an OO approach using instances makes sense for appropriate problems. The `Forth` problem is a good one to assert a class solution. Otherwise, it ends up with a pure function being shoehorned into an instance.

Having mentored many solutions already where I've had to explain the prototype and helping students understand what `class` and `new` does in JavaScript/ECMAScript, I can definitely say that the teaching is there.

**Comment by kybernetikos** [comment] 2018-07-23 19:18
Agreed.  I'm sure hard-core functionistas will disagree with me, but things like Forth where state is required to be maintained across invocations make perfect sense to approach in an OO way, and I have no problem with using 'new' in such cases.

Trying to get people to be skeptical of state, and to avoid it where it's possible to is in my opinion an important road for programmers to follow as they go from novice to skilled, so obviously I'm going to be quite frustrated when the problem tests teach bad practices.

**Comment by matthewmorgan** [comment] 2018-07-23 21:36
Great debate, and worth having for sure.

I would point out that functions are simply objects in JavaScript, with (as mentioned above) the special property of having a constructor, IE, `new` gives you back an instance of the function.

`Leap`, for example, could be solved using anonymous functions and objects very simply:

```javascript
export default year => ({isLeap: () => year % 400 === 0 || year % 4 === 0 && year % 100 !== 0})
```

That's not a whole lot different than:

```javascript
export default year =>  year % 400 === 0 || year % 4 === 0 && year % 100 !== 0
```

except that it requires `new` to be used.  That doesn't seem like a heavy burden for a newcomer, does it?

I think any changes to the track just need to support our goal of exposing as many features as we can to the users.  They'll need those skills as professional developers.

**Comment by c-dante** [comment] 2018-07-23 22:01
@matthewmorgan you REALLY need to be careful! If you try to run that in modern ECMAScript, it will crash and throw on `new` when passed an arrow function!

```
$ node -v       
v10.1.0
$ node   
> let x = year => ({isLeap: () => year % 400 === 0 || year % 4 === 0 && year % 100 !== 0})
undefined
> new x()
TypeError: x is not a constructor
> 
```

So, no, it is not equivalent! The reason something like that *might* work is because babel or similar is transpiling your code into:

```js
export default function(year) { ... }
```

Which would work when called with new.

**Comment by matthewmorgan** [comment] 2018-07-24 00:43
@c-dante I appreciate your careful scrutiny, and you make an excellent point.  

We welcome new ideas and discussions about how to improve the track, and we even more heartily welcome PRs ;)  Don't take anything I've said or am about to say as anything but well-intentioned debate.

Classes are just functions, and functions are just objects, and my example was intended to illustrate that.  One of the beauties of JS is the treatment of functions as first class objects, and classes are recently spun sugar on top.

The _explicit goal_ of this track is to encourage and allow the development of code that will be transpiled, since this is now a common part of the modern JavaScript development workflow.  It's one of the main reasons the JavaScript track is being deprecated in favor of this one.  Even so, I didn't realize that function wouldn't run without transpilation, so I learned something.  :)

The debate about OO vs functional feels a little akin to a political or religious debate, and unlikely to be settled to the satisfaction of zealots of either stripe.  The reality is that both approaches are valid, useful, and found abundantly in the wild, and I strongly reject preferring one approach over another in a language that has always accommodated both.  The track should have examples of both, and from time to time require one or another.  Sometimes that's the way the exercise is because that's the way that someone (often I) wrote it at one point in time when they had a little time to do so.  

Having said all of the above things, I don't think we should make things more complicated for new users, or rather, complicated without benefit to the users. Ideally, the entry path to the track should be challenging enough to be interesting and to promote growth at every step.

It's a certainty that existing test APIs could be edited to encourage a better fit between a given problem and a given test suite.  In my ideal world, those changes would go hand in hand with a plan for the track that introduces concepts to continually challenge the user as they get deeper in to the track.

I know that I and the other maintainers would welcome specific proposals on what to change and how, especially if help executing the changes was offered.  

Thank you!

**Comment by xarxziux** [comment] 2018-08-13 09:00
I know I'm a little late to this discussion, but having gone a little way down both the student and mentoring routes I'd like to express my opinions on this.

In very general, simplistic terms, there are two types of exercises: those that ask you to accept a value and return an answer, and those that ask you take some initial state and return an interface that performs some operations on that state.  The first exercise on the track, Leap, is an example of the first kind.  The Queen Attack exercise falls into the second category as you have to provide the functions white, black, canAttack and toString on the initial board definition.

Taking the first exercise, in some languages this is a one-liner and it could be in JavaScript too, but there's a disconnect between the requirements and the unit tests - you could have code that solves the problem but isn't framed correctly to pass the unit tests.  Why should you have to declare a function that sets some internal state and then add a prototype that operates on that state, when you could simply expose a one-line function that performs the same action?  OOP design has it's place, but this isn't it.

Therefore I would like to propose a change to the design philosophy of the exercises on this track;
- If the exercise can be solved by taking a value and returning another value, then the unit tests should only expect the student to export a function.
- If the exercise specifically asks you to accept some initial state and then provide operations on that state then the unit tests should expect the student to export a class.

FP and OOP both have their strengths and weaknesses.  Adopting the philosophy above would, I believe, teach student that JavaScript readily supports both paradigms but would also encourage them to use the right tool for the right job.

**Comment by coagmano** [comment] 2018-08-15 05:15
Just started mentoring, and the first two submissions on Leap (in the Javascript stream) that I saw were totally bewildered that they had to define a function, then another function on the prototype (ie, a class) to implement a simple method

Keeping things simple is not just good for learning, but general development as well. So I agree with @xarxziux's comments about getting learners to use the right tool for the job

**Comment by c-dante** [comment] 2018-08-15 13:45
Can we just revert this commit: 02c126beac218bf10fa25f45e8475648e33e65cf

I think from this discussion, and as a learning tool, consistency in how to solve the exercise isn't great -- we should expose the idiomatic way a language solves a problem. It's a learning opportunity to discover a simple function solution as well as a more complex class solution.

**Comment by tejasbubane** [comment] 2018-08-15 17:33
I seem to like @xarxziux's comment [here](https://github.com/exercism/ecmascript/issues/274#issuecomment-412453179). What do others think @exercism/javascript ?

**Comment by tejasbubane** [comment] 2018-08-24 17:33
I see a bunch of PRs waiting. Can others at @exercism/javascript chime in and decide what to do here?

**Comment by tejasbubane** [comment] 2018-09-10 11:49
Thanks for all those PRs @xarxziux! Now that we have decided to remove classes, should we close this and create another issue with list of exercises pending conversion so people can pick one-by-one?

**Comment by xarxziux** [comment] 2018-09-10 21:44
I've no problem with that.  I've re-factored most of the core exercises.  I'm not sure there's an awful lot of value in fixing all the side ones as well.

**Comment by matthewmorgan** [comment] 2018-09-19 01:52
Thanks to @tejasbubane and @xarxziux for the considerable effort exerted to make this happen.  +++

**Closed by matthewmorgan** 2018-09-19 01:52 UTC
