### ISSUE TITLE
Bug: Translation Service - Untranslatable is not defined

### ISSUE THREAD

**Issue by khendrikse** [exercism/javascript#1549] opened 2021-12-02 18:26 UTC
Hi! I have noticed through a friend and myself doing this exercise that the error `Untranslatable` that has to be used in step 4 is not defined in the `service.js` file. It is in the `errors.js` file, but it is not coming through. This makes the following error happen when the error is used in step 4: 

```
ReferenceError: Untranslatable is not defined
    at <solution>/service.js:105:30
```

**Comment by khendrikse** [comment] 2021-12-02 19:30
@junedev I’m afraid this is not fixed by #1550. That was another problem that was so easy to fox I did not make an issue for it :)

**Comment by junedev** [comment] 2021-12-02 19:34
Oh, sorry. My mistake. 🙈 Somehow I thought there was an issue for that PR as well.

**Comment by SleeplessByte** [comment] 2021-12-03 05:26
errors.js is likely missing from the appriopiate files / solution / editor / whatever array in the config. This exercise was created before any of that existed cc @junedev

**Comment by junedev** [comment] 2021-12-08 19:57
To me it looks like it's possible to solve the exercise without knowledge of these specific error classes as they are not used in our example solutions. My guess is that using the errors explicitly is nevertheless a reasonable solution so yes, we should make sure they are available.

@khendrikse It would be great if you could let us know whether you saw this error when solving the exercise locally or on the website and also provide me with the solution that produces that error.

**Comment by junedev** [comment] 2022-01-30 14:41
The errors file shows up in the editor just fine so that is not the issue here. I checked a couple of community solutions and even though some import the errors, they don't actually use them. I will need some more time to investigate this and determine why the errors are not needed to solve the exercise even though the instructions sound like they are needed (might be an issue with the test cases) and try to reproduce the error reported in this issue.

@khendrikse In case you are still around, would be great if you could give some more details where and how you encountered the issue (see request above).

**Comment by khendrikse** [comment] 2022-02-01 09:51
Hey @junedev sorry for the long delay! I encountered it while solving the exercise on the website.

This solution triggered the error:

```
/// <reference path="./global.d.ts" />
// @ts-check
//
// The lines above enable type checking for this file. Various IDEs interpret
// the @ts-check and reference directives. Together, they give you helpful
// autocompletion when implementing this exercise. You don't need to understand
// them in order to use it.
//
// In your own projects, files, and code, you can play with @ts-check as well.

export class TranslationService {
  /**
   * Creates a new service
   * @param {ExternalApi} api the original api
   */
  constructor(api) {
    this.api = api;
  }

  /**
   * Attempts to retrieve the translation for the given text.
   *
   * - Returns whichever translation can be retrieved, regardless the quality
   * - Forwards any error from the translation api
   *
   * @param {string} text
   * @returns {Promise<string>}
   */
  free(text) {
    return this.api.fetch(text).then(({translation}) => translation)
  }

  /**
   * Batch translates the given texts using the free service.
   *
   * - Resolves all the translations (in the same order), if they all succeed
   * - Rejects with the first error that is encountered
   * - Rejects with a BatchIsEmpty error if no texts are given
   *
   * @param {string[]} texts
   * @returns {Promise<string[]>}
   */
  batch(texts) {
    const promises = texts.map(text => new Promise((resolve, reject) => {
      this.free(text).then(res => resolve(res)).catch(err => reject(err))
    }))
    return texts.length > 0 ? Promise.all(promises).catch(err => {throw err}) : Promise.reject(new BatchIsEmpty)
  }

  /**
   * Requests the service for some text to be translated.
   *
   * Note: the request service is flaky, and it may take up to three times for
   *       it to accept the request.
   *
   * @param {string} text
   * @returns {Promise<void>}
   */
  request(text, retries = 3, error) {
    return new Promise((resolve, reject) => {
     this.api.request(text, (err1) => {
        if (err1) {
          this.api.request(text, (err2) => {
            if (err2) {
              this.api.request(text, (err3) => {
                if (err3) {
                  reject(err3)
                }
                else {
                  resolve();
                }
              });
           }
            else {
              resolve();
            }
         });
        }
       else {
         resolve()
       }
     })
    })
  }

  /**
   * Retrieves the translation for the given text
   *
   * - Rejects with an error if the quality can not be met
   * - Requests a translation if the translation is not available, then retries
   *
   * @param {string} text
   * @param {number} minimumQuality
   * @returns {Promise<string>}
   */
  premium(text, minimumQuality) {
    return new Promise((resolve, reject) => {
      this.api.fetch(text).then(({translation, quality}) => {
        if (quality < minimumQuality) {
          reject(new QualityThresholdNotMet)
        } else {
          resolve(translation)
        }
      }).catch(error => {
        if (error instanceof Untranslatable) {
          reject(error);
        } else {
          this.request(text).then(() => {
            this.api.fetch(text).then(({translation, quality}) => {
              if (quality < minimumQuality) {
              reject(new QualityThresholdNotMet);
            } else {
              resolve(translation);
            }})
          }).catch(error => reject(error))
        }
      })
    })
  }
}

/**
 * This error is used to indicate a translation was found, but its quality does
 * not meet a certain threshold. Do not change the name of this error.
 */
export class QualityThresholdNotMet extends Error {
  /**
   * @param {string} text
   */
  constructor(text) {
    super(
      `
The translation of ${text} does not meet the requested quality threshold.
    `.trim()
    );

    this.text = text;
  }
}

/**
 * This error is used to indicate the batch service was called without any
 * texts to translate (it was empty). Do not change the name of this error.
 */
export class BatchIsEmpty extends Error {
  constructor() {
    super(
      `
Requested a batch translation, but there are no texts in the batch.
    `.trim()
    );
  }
}

```

**Comment by junedev** [comment] 2022-02-01 21:13
@khendrikse Thanks. I understand now. The import statement is missing. This is fixed now via #1644, we added the import statement to the stub as "imports" as a concept are not properly covered in the syllabus yet and are not the focus of the exercise.

You can look in the PR I linked above to see how to fix your code. The fix we applied will not change stubs when the student already started the exercise but everyone who starts this going forward will benefit from the improvement.

Sidenote: There will be another issue regarding a missing test case for the exercise. I will close this one.

**Closed by junedev** 2022-02-01 21:13 UTC

**Comment by SleeplessByte** [comment] 2022-02-02 00:27
@junedev see also my comment in the #1649 issue. We may be able to solve this by _removing_ the imports.

**Comment by junedev** [comment] 2022-02-02 19:05
@khendrikse Just to keep you in the loop: We decided to change the instructions. The new instructions now lead to a solution that does not require checking for the specific error types anymore so the import is not needed.

**Comment by khendrikse** [comment] 2022-02-04 07:36
@junedev awesome thanks :)
