### ISSUE TITLE
CI does not run at all for some PRs

### ISSUE THREAD

**Issue by junedev** [exercism/javascript#1667] opened 2022-02-06 13:43 UTC
Lately, for some PRs CI does not run at all for whatever reason.

Example (https://github.com/exercism/javascript/pull/1663):
![image](https://user-images.githubusercontent.com/12543047/152683620-f2bea3d7-80d6-4c5a-b114-bb141838acb0.png)

**Notice that it says "Checks 0" at the top.**

When I close and open the PR, CI is triggered, all checks run as they should:
![image](https://user-images.githubusercontent.com/12543047/152685140-e987816f-e61e-4a57-8004-cdfb618712d5.png)

We also saw this happening on PRs when someone executed the format action via GitHub. CI was not triggered after that change was added.

**Comment by junedev** [comment] 2022-11-06 09:41
@theomelo I think so but I have not tried recently.

**Comment by theomelo** [comment] 2022-11-06 17:36
I could try creating a few PRs to try to reproduce this issue and report back 👍

**Comment by theomelo** [comment] 2022-11-19 21:41
Based on your screenshots, I'm assuming there has been a few changes in the actions setup since the creation of this issue. For example, all PRs are now being annotated by [pr-commenter](https://github.com/exercism/pr-commenter-action). 

After I created a couple of PRs (https://github.com/exercism/javascript/pull/1994 and https://github.com/exercism/javascript/pull/1997), both of them triggered just one action (the [pre-comment](https://github.com/exercism/javascript/actions/runs/3505071891)). The other actions seem only to run after a maintainer approves them. This flow is already different from the original issue. Therefore, I can't reproduce the same behaviour.

Unless I could "bypass" that restriction and have all actions run when I create a PR, I won't be able to validate they consistently run in all cases. I guess only a maintainer could try to reproduce this issue now. 🙇‍♂️

**Comment by theomelo** [comment] 2022-11-19 21:43
I can still try to help with debugging. Whenever a maintainer creates a PR that doesn't trigger the actions as expected, would you please ping me here (before closing and opening again) so I can check what happens? 🙏

**Comment by SleeplessByte** [comment] 2022-11-21 14:27
![image](https://user-images.githubusercontent.com/1964376/203079639-3a6591ef-16c8-46c9-be99-e8e1bf70769b.png)

That action was already on the Repo when that PR was opened, but it wasn't triggered until the PR was reopened, which is weird. This may be a bug on the GitHub side btw!

**Comment by junedev** [comment] 2022-11-21 19:51
@theomelo The pipeline does not run if you have never contributed to the repository in the past (to avoid that people misuse the CI runners). Have you tried to forking the repo and then opening a PR against your fork and trying to trigger the format flow there? (Not sure this works though.) If this doesn't work, I don't think you can help with this issue currently.

I also think there is some chance this is a GitHub bug.

**Comment by junedev** [comment] 2022-12-08 19:33
The bug only shows up consistently when using the `format` comment action we have set up.

**Comment by SleeplessByte** [comment] 2022-12-09 06:01
After format we must also reopen the PR, which is by design.

However, I noticed that the format command no longer posts the extra comments (started and finished) because of a token related error. We probably need to update the script.

**Comment by SleeplessByte** [comment] 2024-10-18 21:18
I think that most PRs now have this working with the fork caveat still in place.

**Closed by SleeplessByte** 2024-10-18 21:18 UTC
Labels: bug :bug:, x:action/fix, x:knowledge/intermediate, x:status/claimed, x:type/ci
