### ISSUE TITLE
Missing boilerplate code for exercises?

### ISSUE THREAD

**Issue by jsgilberto** [exercism/javascript#545] opened 2018-05-15 18:40 UTC
Some of the exercises don't have a boilerplate code, just the first 3 (http://exercism.io/languages/javascript/exercises)

**Comment by matthewmorgan** [comment] 2018-05-15 20:37
Thanks @jsgilberto for your feedback.  This issue has been discussed before on this track, but has recently come up again here: https://github.com/exercism/javascript/issues/424

I'm going to close this issue as a duplicate of that one.

**Closed by matthewmorgan** 2018-05-15 20:37 UTC
