### ISSUE TITLE
Need tests  for rule 4 in javascript's pig-latin exercise.

### ISSUE THREAD

**Issue by konni2020** [exercism/javascript#577] opened 2018-12-07 00:25 UTC
- Rule 4: If a word contains a "y" after a consonant cluster or as the second letter in a two letter word it makes a vowel sound (e.g. "rhythm" -> "ythmrhay", "my" -> "ymay").

There are no tests for it.

**Comment by tejasbubane** [comment] 2019-01-18 06:51
Duplicate of https://github.com/exercism/javascript/issues/574. Closed by https://github.com/exercism/javascript/pull/575

**Closed by tejasbubane** 2019-01-18 06:51 UTC
